name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run backend ESLint
        run: npm run lint-be
      - name: Run frontend ESLint
        run: npm run lint-fe
